// The cell behind every singleton, stored inline in the container. The resolve path is one
// acquiring atomic load and a field read: no lock, no generic call, no metadata lookup. The lock
// is taken only while the value is first built.

import Synchronization

/// A value built at most once, on first use, then shared. Generated by `@Singleton` and
/// `@Provides(.singleton)`; use it directly only in a hand-written container.
///
/// Noncopyable so it lives inside the container object instead of being a separate allocation;
/// that is also why containers are `final class`es.
public struct Once<Value>: ~Copyable {
  // A class box, because the atomic holds one pointer; `Value` may be a struct or an existential.
  @usableFromInline
  final class Box {
    @usableFromInline let value: Value
    @usableFromInline init(_ value: Value) { self.value = value }
  }

  // A retained `Box`, published with a release store after `value` is written and read with an
  // acquire load, so a reader that sees the pointer sees the value.
  @usableFromInline let published: Atomic<UnsafeRawPointer?>
  // Serialises the first build so it runs once even under contention; never touched afterwards.
  @usableFromInline let building: Mutex<Void>

  public init() {
    published = Atomic(nil)
    building = Mutex(())
  }

  deinit {
    if let raw = published.load(ordering: .acquiring) {
      Unmanaged<Box>.fromOpaque(raw).release()
    }
  }

  /// The value, built with `make` the first time.
  @inlinable @inline(__always)
  public func get(_ make: () -> Value) -> Value {
    if let raw = published.load(ordering: .acquiring) {
      return Unmanaged<Box>.fromOpaque(raw).takeUnretainedValue().value
    }
    return build(make)
  }

  @usableFromInline @inline(never)
  func build(_ make: () -> Value) -> Value {
    // A cycle through this entry re-enters here and traps on the non-recursive lock instead of
    // recursing forever; `@Container` and `injecta-check` reject cycles before that.
    building.withLock { _ in
      if published.load(ordering: .acquiring) == nil { publish(make()) }
    }
    return Unmanaged<Box>.fromOpaque(published.load(ordering: .acquiring)!).takeUnretainedValue().value
  }

  /// Sets the value before anything reads it (an override); ignored once the value exists.
  public func seed(_ value: Value) {
    building.withLock { _ in
      if published.load(ordering: .acquiring) == nil { publish(value) }
    }
  }

  /// Whether the value has been built or seeded.
  public var isBuilt: Bool { published.load(ordering: .acquiring) != nil }

  @usableFromInline
  func publish(_ value: Value) {
    let box = Unmanaged.passRetained(Box(value))
    published.store(UnsafeRawPointer(box.toOpaque()), ordering: .releasing)
  }
}

// Sharing the cell shares `Value`, so the cell is Sendable exactly when the value is. A container
// holding a non-Sendable singleton is therefore not Sendable either, and Swift 6 keeps it on one
// isolation domain (mark such containers `@MainActor`).
extension Once: @unchecked Sendable where Value: Sendable {}
