// injecta-check OUTPUT FILE... : checks every `@Container` of a target against every
// `@Injectable` in it (missing entries and cycles through auto-wired types, captive transients),
// prints `file:line:column: error:` lines Xcode and SwiftPM show inline, and writes OUTPUT: the
// `Needs` conformances of the auto-wired types, which the target compiles. Exits 1 on an error.

import Foundation
import InjectaSyntax
import SwiftParser

let arguments = CommandLine.arguments.dropFirst()
guard let output = arguments.first else {
  FileHandle.standardError.write(Data("usage: injecta-check OUTPUT.swift FILE.swift...\n".utf8))
  exit(2)
}

var scan = TargetScan()
for file in arguments.dropFirst() {
  guard let source = try? String(contentsOfFile: file, encoding: .utf8) else {
    // Fail open: an unreadable file is the compiler's to report, not a reason to stop the build.
    print("\(file):1:1: warning: injecta: could not read this file; it was not checked")
    continue
  }
  scan.add(Parser.parse(source: source), file: file)
}

let diagnostics = scan.diagnostics()
for diagnostic in diagnostics { print(diagnostic.line) }

let generated = (
  [
    "// Generated by injecta-check: \(scan.containers.count) container(s), "
      + "\(scan.injectables.count) injectable type(s). Do not edit."
  ] + scan.conformances()
).joined(separator: "\n") + "\n"
do {
  // Unchanged output keeps its timestamp, so the target is not recompiled for nothing.
  if (try? String(contentsOfFile: output, encoding: .utf8)) != generated {
    try generated.write(toFile: output, atomically: true, encoding: .utf8)
  }
} catch {
  print("error: injecta: cannot write \(output): \(error)")
  exit(1)
}
exit(diagnostics.contains { $0.isError } ? 1 : 0)
